version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: taskvip-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: taskvip
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - taskvip-network

  backend:
    build: ./backend
    container_name: taskvip-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/taskvip?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      JWT_EXPIRE: 7d
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - taskvip-network
    volumes:
      - ./backend/logs:/app/logs

  frontend:
    build: ./frontend
    container_name: taskvip-frontend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - taskvip-network

  nginx:
    image: nginx:alpine
    container_name: taskvip-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - taskvip-network

volumes:
  mongodb_data:

networks:
  taskvip-network:
    driver: bridge
